name: server-main

on:
  push:
    branches: ["main"]
    paths: ["server/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
      working-directory: server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: npm ci

      - run: npm run lint
